# Config file for message queue service

# Port number for the message queue service
queue_port: 7500
# Port number for the authentication service
auth_port: 8000

# All the queue data
queues_file:
  persist_interval: 30
  file_path: queues.json
  max_queue_size: 5

# Path to the directory to store the queue data
# it is in the same directory
data_dir: ./data

# Roles allowed to access the message queue service
manipulation_role:
  - Administrator
  - Manager

creation_role:
  - Administrator

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s [%(levelname)s] %(message)s'
  file_path: message_queue.log